### ISSUE TITLE
Non-Integer patch-size leads to import-a:pcolors-rgb not filling the complete view

### ISSUE THREAD

**Issue by gabriel-wurzer** [NetLogo/ImportA-Extension#2]
### Summary 
import-a:pcolors has an error when a non-integer patch-size is given. We have a 145x113 pixels png and a world that is exactly that size (origin at lower-left corner, 0 0 -> 144 112). Assumption would be that every patch is filled. For integer patch-size this is indeed the case, the error occurs when patch-size is not an integer (in my case 2.7586206896551726). The error does not occur in import-pcolors, only in import-a:pcolors.

### Details
I have produced a minimal working example which shows  `import-pcolors` vs. `import-a:pcolors`  --> [import-a pcolors patchsize.zip](https://github.com/NetLogo/NetLogo/files/8612741/import-a.pcolors.patchsize.zip). 

After unzipping, press `setup-import-pcolors` and see that all is fine, then press `setup-import-a-pcolors` and choose 145x113pixels.png. You will see the following image:

![import-a-pcolors](https://user-images.githubusercontent.com/35217861/166420814-0f214f18-eddf-4324-aef8-c003283f5375.png)

System Info:

NetLogo 6.2.0 (December 22, 2020)
Extension API version: 6.1
OpenJDK 64-Bit Server VM 1.8.0_275 (BellSoft; 1.8.0_275-b01)
operating system: Windows 10 10.0 (amd64 processor)
Scala version 2.12.12
Java heap: used = 37 MB, free = 407 MB, max = 910 MB

JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)

Extensions:
Import-A Extension 1.0.6 (=latest version)
Fetch Extension 1.0.4 (=latest version)

_Originally posted by @gabriel-wurzer in https://github.com/NetLogo/NetLogo/issues/2028#issuecomment-1115837207_

**Comment by gabriel-wurzer** [comment]
(corrected the uploaded zip file - thanks goes to @brandesNW for dropping me a line)

**Comment by TheBizzle** [comment]
Thanks for another really helpful and informative bug report!

In a future version of `import-a` (or should you choose to build a version from the latest source code), this bug will no longer be present.

The issue here stems from oddities of IEEE floating point arithmetic.  This system that is universally used by modern computers for performing arithmetic can lead to some surprising results, which is why most programming languages you'll ever use will tell you things like `0.1 + 0.2` resulting in `0.30000000000000004`.

The example that I just gave is an especially odd one, but these errors usually occur more often as floating-point numbers gain more digits.  In the case of your bug, the patch size value that was required was incredibly specific.  `2.7586206896551726` would trigger it, but `2.758620689655172` would not.  And none of the other truncations of that number would cause it, either.  (Which really causes me to wonder how you even came across this number. :thinking: )  

My solution to this was to accept that patch sizes are rarely large numbers, and so, when calculating some values off of the patch size, rescale them into a range that is less likely to cause errors.

Regardless, a quick fix that you can use, without you updating your version of `import-a` at all, would be to change your `patch-size` by an imperceptibly small amount, truncating some of the right-most decimal places.

**Comment by gabriel-wurzer** [comment]
Dear @TheBizzle,
The patch-size I chose was the simple result of dividing 400px (which is what I wanted the view to be on screen) by 145px (the width of my image). That this would unleash hell was not intended, *bump*, thank you for fixing the error and I will surely keep this in mind for the future, should have paid better attention to the course on numerics :-) cheers gabriel
